### ISSUE TITLE
How to insert touchscreen buttons

### ISSUE THREAD

**Issue by holli77** [bartaz/impress.js#449]
Hey there,
I want to make my presentation to work on a touchscreen TV.

Now the problem is that I need to insert some sort of arrow keys left/right on the screen which appear all the time (also a key which replaces the ESC function), so that I  won't need to use the keyboard at all. 

The normal "swipe"-function doesn't really work, which on tablets/phones/touchscreens,replaces the arrow keys. Some times it zooms in to the slides/steps which are for example in the background (further behind on the Z-axis)

Does somebody have a solution? Will I need to insert those keys with a link to the next slide on everyslide, if I want to replace the right-arrow-key from my keyboard. (i.e. in Step1 a link to step2, in step2 a link to step3...etc.)

or do you know any possibility, maybe some sort of application for Firefox/Chrome where it exists already to have those keys, independently from the programmation of the html/css, in the foreground of my "desktop".

Thanks.

**Comment by FranzSkuffka** [comment]
On line 766 of impress.js it says that there are touch event handlers bound to the right and left third of the screen, doing exactly what you want.

Have you checked that out yet?

**Comment by bartaz** [comment]
By default touch events are bound to left and right side of the screen (without any buttons).
So if the touchscreen TV properly triggers touch events it should already work.

In case it doesn't - you don't need to create buttons on every slide.
You should create your buttons somewhere outside the impress root element and position them absolutely. Then you have to bind a function on click on these buttons to call `next()` or `prev()` API on impress.

**Comment by holli77** [comment]
Thank you  very much guys.
Since this time I found a solution similar to the second possibility from Bartaz.
But Yes I haven't seen the line 766, I was always trying to slide for the next step.

Good Work!
