### ISSUE TITLE
I could help review issues and pull requests, if you need help.

### ISSUE THREAD

**Issue by Terrycloth** [bartaz/impress.js#456]
@bartaz 
Hello! I'm of course very happy with impress.js -- but I notice that the most recent committed changes have only corrected minor typos in the code comments. Yet there are a bunch of open issues and pull requests.

Maybe this is because you're too busy with other things to keep up with impress.js on GitHub? If so, then I could help review and test pull requests.

Or maybe you feel like you're happy with how impress.js currently works and you just don't want to change it anymore? If so, that's fine too, and I will just start a fork for my own use.

Please let me know what you think.

Thanks!

**Comment by FagnerMartinsBrack** [comment]
Related: https://github.com/bartaz/impress.js/issues/435

**Comment by Terrycloth** [comment]
Ah, thanks.
