### ISSUE TITLE
Feature request : move background with change in step

### ISSUE THREAD

**Issue by anwargm** [bartaz/impress.js#483]
Can we zoom in/Zoom out the background image along with scaling in/scaling out of steps.
eg. 
![ci-1](https://cloud.githubusercontent.com/assets/1948036/8124182/f08c5852-10f4-11e5-9f06-5f6f7e6f7957.png)
First image is intro page of presentation. And second image is next slide in same presentation. 
![ci-2](https://cloud.githubusercontent.com/assets/1948036/8124192/154e9c4a-10f5-11e5-9cee-eee0e2b05e51.png)

But if you observe the the backgroung of the slide, it has been zoomed in/out as well.
Can we do that? 
I am not sure if this is already available or there is a workaround available. If there is one, please let me know.

**Comment by bartaz** [comment]
This is currently not possible.

'Slides' in impress.js are 'floating' positioned in 3D space so there is no easy way to create a background that will move and scale together with slides.

I haven't tried that but some workaround may be to create a one big slide with the background (for example the first one or last one) and place all the other slides as small on top of this background slide.
In such case this 'background' slide will be also positioned in 3D with other slides and should zoom and move when slides are changed.

But I can't promise if this would really work and look good - you may get some graphic glitches or pixelated background when it's scaled to be big.

**Comment by anwargm** [comment]
I'll try the workaround. 
And THANK YOU for the impressive impress.js

**Comment by blauertee** [comment]
In my case I don't want to zoom in on specific details in the Background I just want the Background to kind of align with the zoom level of the viewport / camera. Is there a way to get the current zoom level of the camera?
Then I could just set the background size to some factor times the zoom level.

**Comment by henrikingo** [comment]
@blauertee 

Purely off the top of my head, without testing: Get the id of the current step from the `location.hash`, then read its scale attribute.

var id = window.location.hash
var step = document.getElementById(id)
var scale = step.dataset.scale
